//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta.
//     Versão Executável:4.0.30319.34014
//
//     Modificações neste arquivo podem causar comportamento inadequado e serão perdidas caso
//     o código seja recriado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDF.Properties
{


    /// <summary>
    ///   Uma classe de recurso fortemente tipada, para pesquisar cadeias de caracteres localizadas, etc.
    /// </summary>
    // Esta classe foi gerada automaticamente pela StronglyTypedResourceBuilder
    // classe via ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um membro, edite seu arquivo .ResX e execute novamente ResGen
    // com a opção /str, ou recompile seu projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Retorna a instância ResourceManager em cache usada por esta classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((resourceMan == null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Substitui a propriedade CurrentUICulture da thread atual para todas
        ///   pesquisas de recurso usando esta classe de recurso fortemente tipada.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
    }
}
